# Generated by Django 3.1.5 on 2022-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
